server:
  port: 8080
  host: localhost

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: 261813
  dbname: course_schedule
  charset: utf8mb4
  parseTime: true
  loc: Local

auth:
  jwtSecret: "your-secret-key-change-this-in-production"
  jwtDuration: 24 # 令牌有效期（小时）